### ISSUE TITLE
General Kaiwa 2.0 development plan

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/kaiwa#155]
Kaiwa 2.0 will not be compatible with 1.0 config format and will be rewritten in TypeScript + React.

### Plan

- [ ] #143: XMPP server connection
- [ ] #144: Cancel connection button
- [ ] #52: Incorrect login is unclear
- [ ] Show contact list
- [ ] Show chat window
- [ ] Settings page
